# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Clapmera' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GoogleAnalytics', '~> 3.17'
  pod 'FBSDKCoreKit', '~> 4.27.1'
  pod 'FPPopover', '~> 1.4'
  # Pods for Clapmera

  target 'ClapmeraTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
