# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'Clapmera' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  #pod 'BFGallery' , :git => "https://github.com/darioalessandro/BlackFireGallery.git", :tag => "0.1.2"
  # Pods for Clapmera
  pod 'GoogleAnalytics', '~> 3.17'
  pod 'FBSDKCoreKit', '~> 4.25'

end

#target 'clapmera' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for clapmera

#end
